"""empty message

Revision ID: 06250698bb62
Revises: 3b0802269b62
Create Date: 2019-01-19 12:22:16.055483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06250698bb62'
down_revision = '3b0802269b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
